### ISSUE TITLE
MaxDate and minDate issue in picker

### ISSUE THREAD

**Issue by AndroiDev2015** [keyrunHORNET/date_picker_converter#1]

**Comment by keyrunHORNET** [comment]
I will check and let you know soon

**Comment by keyrunHORNET** [comment]
thanks for pointing out this issue, there has been some inconsistency with the representive of month in int.
Some method takes 0-11 whereas some take 1-12. I will fix that soon. meanwhile you can workaround with passing month=month-1

let me know if this solves your problem

**Comment by shakya001** [comment]
Also, I've got an issue. How can we set the datepicker selected to specific month only. For example : If we want to pick the date from month Shrawan,2018 only how can we disable the icons "<" and " > " that is used for chaning the months?

**Comment by keyrunHORNET** [comment]
you can achieve that by using
 `setSelectableDays(List<Model> days)`

pass the list with dates of shrawan

**Comment by shakya001** [comment]
I've now got all the list of Shrawan month dates but List<Model> only takes the Model paramter.
How can I change that ??

` List<Model> selectableDays = new ArrayList<Model>();
        for(int i = 1; i <= end_day ; i++)
        {
            selectableDays.addAll((Collection<? extends Model>) new Model(end_year,end_month,end_day));
        }`

Here end_year, end_month, end_day all are in nepali date format

**Comment by shakya001** [comment]
I tried to manually insert 2075 year 3 month list, but the calendar only shows up Bhadra, is there any thing wrong in my code ?

 List<Model> selectableDays = new ArrayList<Model>();
        for(int i = 1; i <= end_day ; i++) // end_day value is 32
        {
            selectableDays.add(new Model(2075,3,end_day));
        }
// setting selectable days.
 dpd.setSelectableDays(selectableDays);

**Comment by shakya001** [comment]
Could you please check the above condition ?
