### ISSUE TITLE
new version crashing 2.1

### ISSUE THREAD

**Issue by SynergySaugat** [keyrunHORNET/date_picker_converter#11]
Caused by: java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.

**Comment by keyrunHORNET** [comment]
can you please explain a little bit more? What were you trying to do, or anything, that can help me debug!

**Comment by SynergySaugat** [comment]
i was using this library with older version of gradle 2.3.3 and buildtoolversion 26.0.1 and gave this error..
but i was able to use after upgrading the gradle to v3.x and buildtoolversion 28.0.0

**Comment by keyrunHORNET** [comment]
Cool. I am in need of contributor. And i can use your help. Just remember "You can make a library if you can code"

I have few features in mind for later version of this library.

And for nepali text in picker ,if you change language of phone to nepali from settings, it works.

If you are really intrested in improving this library, feel free to do so. fork, clone, pull, push whatever you want.

If you want you can make pull request as well.

If there is anything else, you think i help you in, regarding this library or project. Send me a mail.
