### ISSUE TITLE
Nepali year only goes until 2000

### ISSUE THREAD

**Issue by jjongko** [keyrunHORNET/date_picker_converter#12]
Hi I was trying this library on a Nursing app we were making for Nurse Association of Nepal, however, the nurses were complaining that the year only goes to 2000, apparently they were profiling a very old person.  When they tried using the AD date, the converter failed.  Looking at some online date converters the date went below 2000 so I guess that was the issue.  Looking at the source code, it seems to be a hard limit that was put in.   Would it be possible to lower the min date?  I've seen some other converters go to 1970 though i'm not sure how hard that would be to incorporate

**Comment by keyrunHORNET** [comment]
I will look into it and let you know as soon as possible.

**Comment by jjongko** [comment]
This was the table data that I saw that went to 1970, not sure if its useful though

https://github.com/bahadurbaniya/Date-Converter-Bikram-Sambat-to-English-Date/blob/master/src/main/java/np/com/converter/date/nepali/Lookup.java

**Comment by keyrunHORNET** [comment]
Link you just provided is the solution. I just need some time to reflect
that in code. And i really am in hectic and busy  schedule right now.

If you have some time, like a month, i will update it for you. Or you can
help me by changing it yourself and making  a pull request.

All you have to do is update HashMap in DateConverter file and change
minimum and maximum date in picker.

**Comment by jjongko** [comment]
I updated the hashmap and the limit ranges.  However, the startWeekDayMonthMap has no data for 1970-1999 since I don't know what goes there.  I was hoping it wasn't called anywhere but it looks like it is

**Comment by keyrunHORNET** [comment]
startweekdaymonthmap is nothing but a weekday of 1st day of every Nepali month in conversion range.
 value range from 1-7 indicating sunday-saturday.

**Comment by jjongko** [comment]
Yes... but how will I get that information?  Sounds like I would need to input 30x12 number of 1st day of each month in an online nepali calendar?

**Comment by jjongko** [comment]
Ok I wrote a script to get all the start of month days from https://www.ashesh.com.np/nepali-date-converter.php for each month from 1970 to 1999 and for 2000 (for verification with the original code)

**Comment by jjongko** [comment]
Ok it looks like I got it to work

**Comment by keyrunHORNET** [comment]
Can you push the code?

**Comment by jjongko** [comment]
not too familiar with this system, I just downloaded the entire project.  I can send you the 2 files I edited if you want

**Comment by keyrunHORNET** [comment]
Sure.
