### ISSUE TITLE
 java.lang.NullPointerException: Attempt to read from null array

### ISSUE THREAD

**Issue by itsme801** [keyrunHORNET/date_picker_converter#2]
I used your code to display the a simple datepicker but it says, 
![capture](https://user-images.githubusercontent.com/41985969/43506648-68441750-958a-11e8-81b0-25abfcd46a19.PNG)

Can you figure out why is this issue seen ? I've not added anything just simple datepicker only

**Comment by itsme801** [comment]
![test](https://user-images.githubusercontent.com/41985969/43507203-2602ec98-958c-11e8-952c-6dd5a374511b.png)

**Comment by keyrunHORNET** [comment]
let me check and get back to you

**Comment by itsme801** [comment]
In that screenshot i forgot to include, 
Calendar now = Calendar.getInstance(); [included in my code though]

**Comment by keyrunHORNET** [comment]
Try dpd.show() on user click event instead. and let me know after

**Comment by itsme801** [comment]
No its not working now also, I've called the method in menuItem onclick, but the app crashed with the same issue

**Comment by itsme801** [comment]
Can you suggest any solutions?

**Comment by keyrunHORNET** [comment]
i'll let you know, I am kind of Busy right now. Meanwhile you can fork this repo and play around with code to fit your need.

**Comment by rokayaHK** [comment]
Hello @itsme801 , have you solved the issue?? I am facing the same issue.

**Comment by itsme801** [comment]
@rokayaHK  no, i tried everything possible, but the issue is not solved
