### ISSUE TITLE
Dependency Resolution issue

### ISSUE THREAD

**Issue by developerRojina** [keyrunHORNET/date_picker_converter#20]
When adding this library in gradle verion: 7.0.1 It is giving dependency resolution issue:

If I don't use this library the build is successful without any issues

* What went wrong:
Execution failed for task ':app:checkDebugDuplicateClasses'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.CheckDuplicatesRunnable
   > Duplicate class org.intellij.lang.annotations.Flow found in modules jetified-annotations-16.0.1 (org.jetbrains:annotations:16.0.1) and jetified-annotations-java5-15.0 (org.jetbrains:annotations-java5:15.0)
     Duplicate class org.intellij.lang.annotations.Identifier found in modules jetified-annotations-16.0.1 (org.jetbrains:annotations:16.0.1) and jetified-annotations-java5-15.0 (org.jetbrains:annotations-java5:15.0)
     Duplicate class org.intellij.lang.annotations.JdkConstants found in modules jetified-annotations-16.0.1 (org.jetbrains:annotations:16.0.1) and jetified-annotations-java5-15.0 (org.jetbrains:annotations-java5:15.0)
     Duplicate class org.intellij.lang.annotations.JdkConstants$AdjustableOrientation found in modules jetified-annotations-16.0.1 (org.jetbrains:annotations:16.0.1) and jetified-annotations-java5-15.0 (org.jetbrains:annotations-java5:15.0)
     Duplicate class org.intellij.lang.annotations.JdkConstants$BoxLayoutAxis found in modules jetified-annotations-16.0.1 (org.jetbrains:annotations:16.0.1) and jetified-annotations-java5-15.0 (org.jetbrains:annotations-java5:15.0)
     Duplicate class org.intellij.lang.annotations.JdkConstants$CalendarMonth found in modules jetified-annotations-16.0.1 (org.jetbrains:annotations:16.0.1) and jetified-annotations-java5-15.0 (org.jetbrains:annotations-java5:15.0)
     Duplicate class org.intellij.lang.annotations.JdkConstants$CursorType found in modules jetified-annotations-16.0.1 (org.jetbrains:annotations:16.0.1) and jetified-annotations-java5-15.0 (org.jetbrains:annotations-java5:15.0)
     Duplicate class org.intellij.lang.annotations.JdkConstants$FlowLayoutAlignment found in modules jetified-annotations-16.0.1 (org.jetbrains:annotations:16.0.1) and jetified-annotations-java5-15.0 (org.jetbrains:annotations-java5:15.0)
     Duplicate class org.intellij.lang.annotations.JdkConstants$FontStyle found in modules jetified-annotations-16.0.1 (org.jetbrains:annotations:16.0.1) and jetified-annotations-java5-15.0 (org.jetbrains:annotations-java5:15.0)
     Duplicate class org.intellij.lang.annotations.JdkConstants$HorizontalAlignment found in modules jetified-annotations-16.0.1 (org.jetbrains:annotations:16.0.1) and jetified-annotations-java5-15.0 (org.jetbrains:annotations-java5:15.0)
     Duplicate class org.intellij.lang.annotations.JdkConstants$InputEventMask found in modules jetified-annotations-16.0.1 (org.jetbrains:annotations:16.0.1) and jetified-annotations-java5-15.0 (org.jetbrains:annotations-java5:15.0)
     Duplicate class org.intellij.lang.annotations.JdkConstants$ListSelectionMode found in modules jetified-annotations-16.0.1 (org.jetbrains:annotations:16.0.1) and jetified-annotations-java5-15.0 (org.jetbrains:annotations-java5:15.0)
     Duplicate class org.intellij.lang.annotations.JdkConstants$PatternFlags found in modules jetified-annotations-16.0.1 (org.jetbrains:annotations:16.0.1) and jetified-annotations-java5-15.0 (org.jetbrains:annotations-java5:15.0)
     Duplicate class org.intellij.lang.annotations.JdkConstants$TabLayoutPolicy found in modules jetified-annotations-16.0.1 (org.jetbrains:annotations:16.0.1) and jetified-annotations-java5-15.0 (org.jetbrains:annotations-java5:15.0)
     Duplicate class org.intellij.lang.annotations.JdkConstants$TabPlacement found in modules jetified-annotations-16.0.1 (org.jetbrains:annotations:16.0.1) and jetified-annotations-java5-15.0 (org.jetbrains:annotations-java5:15.0)
     Duplicate class org.intellij.lang.annotations.JdkConstants$TitledBorderJustification found in modules jetified-annotations-16.0.1 (org.jetbrains:annotations:16.0.1) and jetified-annotations-java5-15.0 (org.jetbrains:annotations-java5:15.0)
     Duplicate class org.intellij.lang.annotations.JdkConstants$TitledBorderTitlePosition found in modules jetified-annotations-16.0.1 (org.jetbrains:annotations:16.0.1) and jetified-annotations-java5-15.0 (org.jetbrains:annotations-java5:15.0)
     Duplicate class org.intellij.lang.annotations.JdkConstants$TreeSelectionMode found in modules jetified-annotations-16.0.1 (org.jetbrains:annotations:16.0.1) and jetified-annotations-java5-15.0 (org.jetbrains:annotations-java5:15.0)
     Duplicate class org.intellij.lang.annotations.Language found in modules jetified-annotations-16.0.1 (org.jetbrains:annotations:16.0.1) and jetified-annotations-java5-15.0 (org.jetbrains:annotations-java5:15.0)
     Duplicate class org.intellij.lang.annotations.MagicConstant found in modules jetified-annotations-16.0.1 (org.jetbrains:annotations:16.0.1) and jetified-annotations-java5-15.0 (org.jetbrains:annotations-java5:15.0)
     Duplicate class org.intellij.lang.annotations.Pattern found in modules jetified-annotations-16.0.1 (org.jetbrains:annotations:16.0.1) and jetified-annotations-java5-15.0 (org.jetbrains:annotations-java5:15.0)
     Duplicate class org.intellij.lang.annotations.PrintFormat found in modules jetified-annotations-16.0.1 (org.jetbrains:annotations:16.0.1) and jetified-annotations-java5-15.0 (org.jetbrains:annotations-java5:15.0)
     Duplicate class org.intellij.lang.annotations.PrintFormatPattern found in modules jetified-annotations-16.0.1 (org.jetbrains:annotations:16.0.1) and jetified-annotations-java5-15.0 (org.jetbrains:annotations-java5:15.0)
     Duplicate class org.intellij.lang.annotations.RegExp found in modules jetified-annotations-16.0.1 (org.jetbrains:annotations:16.0.1) and jetified-annotations-java5-15.0 (org.jetbrains:annotations-java5:15.0)
     Duplicate class org.intellij.lang.annotations.Subst found in modules jetified-annotations-16.0.1 (org.jetbrains:annotations:16.0.1) and jetified-annotations-java5-15.0 (org.jetbrains:annotations-java5:15.0)
     Duplicate class org.jetbrains.annotations.Contract found in modules jetified-annotations-16.0.1 (org.jetbrains:annotations:16.0.1) and jetified-annotations-java5-15.0 (org.jetbrains:annotations-java5:15.0)
     Duplicate class org.jetbrains.annotations.Nls found in modules jetified-annotations-16.0.1 (org.jetbrains:annotations:16.0.1) and jetified-annotations-java5-15.0 (org.jetbrains:annotations-java5:15.0)
     Duplicate class org.jetbrains.annotations.Nls$Capitalization found in modules jetified-annotations-16.0.1 (org.jetbrains:annotations:16.0.1) and jetified-annotations-java5-15.0 (org.jetbrains:annotations-java5:15.0)
     Duplicate class org.jetbrains.annotations.NonNls found in modules jetified-annotations-16.0.1 (org.jetbrains:annotations:16.0.1) and jetified-annotations-java5-15.0 (org.jetbrains:annotations-java5:15.0)
     Duplicate class org.jetbrains.annotations.NotNull found in modules jetified-annotations-16.0.1 (org.jetbrains:annotations:16.0.1) and jetified-annotations-java5-15.0 (org.jetbrains:annotations-java5:15.0)
     Duplicate class org.jetbrains.annotations.Nullable found in modules jetified-annotations-16.0.1 (org.jetbrains:annotations:16.0.1) and jetified-annotations-java5-15.0 (org.jetbrains:annotations-java5:15.0)
     Duplicate class org.jetbrains.annotations.PropertyKey found in modules jetified-annotations-16.0.1 (org.jetbrains:annotations:16.0.1) and jetified-annotations-java5-15.0 (org.jetbrains:annotations-java5:15.0)
     Duplicate class org.jetbrains.annotations.TestOnly found in modules jetified-annotations-16.0.1 (org.jetbrains:annotations:16.0.1) and jetified-annotations-java5-15.0 (org.jetbrains:annotations-java5:15.0)
     
     Go to the documentation to learn how to <a href="d.android.com/r/tools/classpath-sync-errors">Fix dependency resolution errors</a>.

* Try:

**Comment by sayedtalha124** [comment]
I am getting this issue with gradle 7.0.4

**Comment by AadarshaSadan** [comment]
jestha 32 is missing how can i add this
