### ISSUE TITLE
both nepali and english date picker

### ISSUE THREAD

**Issue by sabpou** [keyrunHORNET/date_picker_converter#3]
hi, if i want to display both nepali and english date picker, how can i display english date picker with importing ur library?

**Comment by keyrunHORNET** [comment]
use default android english date picker for that: 

android.app.DatePickerDialog
--

**Comment by sabpou** [comment]
well, there is conflict in the same page if default android datepicker is imported, what would be solution

**Comment by keyrunHORNET** [comment]
use proper package reference in every instance

####FOR NEPALI####
com.hornet.dateconverter.DatePicker.DatePickerDialog nepaliDatePicker=new com.hornet.dateconverter.DatePicker.DatePickerDialog();


####FOR ENGLISH####
android.app.DatePickerDialog englishDatePicker=new android.app.DatePickerDialog(this);

**Comment by keyrunHORNET** [comment]
similarly implement their interfaces as well

**Comment by sabpou** [comment]
thank, will try that
