### ISSUE TITLE
how to get Current year Sunday and Saturday.

### ISSUE THREAD

**Issue by keshavbhusal1** [keyrunHORNET/date_picker_converter#7]

**Comment by keyrunHORNET** [comment]
I dont get it. Current year sunday and saturday! What does that mean?

**Comment by keshavbhusal1** [comment]
how to print current month Sunday and Saturday?

**Comment by keyrunHORNET** [comment]
I don't understand your question. if you are asking me to print something in java, then use
 `System.out.println() `

I am closing this issue. 
hit me on my mail for questions outside the context of this library.
