### ISSUE TITLE
Always Opening Date picker dialog with current date selected only

### ISSUE THREAD

**Issue by shubhamfzd** [keyrunHORNET/date_picker_converter#9]
I am trying to create a date picker dialog with a default selected date but the following code is opening the calendar always with current date selected.

```
DatePickerDialog dialog = DatePickerDialog.newInstance(listener, 2077, 4, 15); 
dialog.show();
```
I have tried passing Model as well but still same issue.

**Comment by keyrunHORNET** [comment]
this issue has been fixed and will be available in new version 2.1
